server:
  port: 10000

spring:
  application:
    name: sc-config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/SolaSJ/SpringCloudConfig/
          searchPaths: config