###

#POST localhost:9003/mail
POST localhost:10000/sc-mail/mail
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "from": "solasj@qq.com",
  "text": "hello world! hello world! hello world! hello world!",
  "to": [
    "solasj@qq.com"
  ],
  "subject": "hello world!"
}

###

GET localhost:9003/mail/1
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

###

#POST localhost:9003/topic/hello world!
POST 172.18.0.3:9003/topic/hello world!
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

###