#
POST localhost:9003/mail
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "from": "solasj@qq.com",
  "text": "hello world! hello world! hello world! hello world!",
  "to": [
    "solasj@qq.com"
  ],
  "subject": "hello world!"
}

###