server:
  port: 9003

spring:
  application:
    name: sc-mail
  mail:
    host: smtp.qq.com
    username: solasj@qq.com
    password: fhqduzyzfdhfbedg
    default-encoding: UTF-8

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

feign:
  hystrix:
    # 开启hystrix的熔断回调
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: refresh, bus-refresh, hystrix.stream

# 自定义配置
mail:
  sender: solasj@qq.com
  receiver: jie.su@karakal.com.cn, solasj@qq.com