eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

hello: hello world, update config!

management:
  endpoints:
    web:
      exposure:
        include: refresh, bus-refresh