eureka:
  client:
    serviceUrl:
      defaultZone: http://sc-registry:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: refresh, bus-refresh, hystrix.stream

hello: hello world, OK!