eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

hello: hello world, config updated again!

management:
  endpoints:
    web:
      exposure:
        include: refresh