server:
  port: 10000

spring:
  application:
    name: sc-proxy

eureka:
  client:
    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
      defaultZone: http://sc-registry:8761/eureka/