eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: refresh, bus-refresh, hystrix.stream, turbine.stream

spring:
  application:
    name: sc-turbine
server:
  port: 8763
turbine:
  aggregator:
    cluster-config: default
  cluster-name-expression: "'default'"
  app-config: sc-mail, sc-order
  combine-host-port: true
