server:
  port: 18763

spring:
  application:
    name: sc-turbine

eureka:
  client:
    serviceUrl:
      defaultZone: http://sc-registry:18761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: refresh, bus-refresh, hystrix.stream, turbine.stream

turbine:
  aggregator:
    cluster-config: default
  cluster-name-expression: "'default'"
  app-config: sc-mail, sc-order
  combine-host-port: true
